export const productsArray = [
  {
    id: 1,
    gender: "men",
    category: "runners",
    brand: "new balance",
    color: "white",
    size: 35,
    price: 23,
    img: require("./Images/1.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 2,
    gender: "men",
    category: "casual",
    brand: "nike",
    color: "gray",
    size: 44,
    price: 30,
    img: require("./Images/2.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 3,
    gender: "women",
    category: "runners",
    brand: "puma",
    color: "white",
    size: 38,
    price: 45,
    img: require("./Images/3.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 4,
    gender: "men",
    category: "basketball",
    brand: "levis",
    color: "gray",
    size: 45,
    price: 75,
    img: require("./Images/4.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 5,
    gender: "women",
    category: "casual",
    brand: "tommy hilfiger",
    color: "blue",
    size: 37,
    price: 37,
    img: require("./Images/5.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 6,
    gender: "men",
    category: "basketball",
    brand: "air jordan",
    color: "gray",
    size: 46,
    price: 37,
    img: require("./Images/6.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 7,
    gender: "women",
    category: "basketball",
    brand: "reebok",
    color: "white",
    size: 41,
    price: 120,
    img: require("./Images/7.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 8,
    gender: "women",
    category: "basketball",
    brand: "reebok",
    color: "green",
    size: 39,
    price: 35,
    img: require("./Images/8.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 9,
    gender: "men",
    category: "runners",
    brand: "reebok",
    color: "blue",
    size: 44,
    price: 45,
    img: require("./Images/9.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 10,
    gender: "men",
    category: "runners",
    brand: "reebok",
    color: "white",
    size: 43,
    price: 67,
    img: require("./Images/10.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 11,
    gender: "men",
    category: "runners",
    brand: "reebok",
    color: "white",
    size: 42,
    price: 55,
    img: require("./Images/11.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 12,
    gender: "men",
    category: "runners",
    brand: "adidas",
    color: "red",
    size: 40,
    price: 97,
    img: require("./Images/12.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 13,
    gender: "men",
    category: "runners",
    brand: "adidas",
    color: "blue",
    size: 44,
    price: 111,
    img: require("./Images/13.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 14,
    gender: "men",
    category: "runners",
    brand: "adidas",
    color: "black",
    size: 43,
    price: 32,
    img: require("./Images/14.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 15,
    gender: "women",
    category: "runners",
    brand: "adidas",
    color: "red",
    size: 39,
    price: 37,
    img: require("./Images/15.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 16,
    gender: "men",
    category: "runners",
    brand: "adidas",
    color: "gray",
    size: 38,
    price: 49,
    img: require("./Images/16.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 17,
    gender: "women",
    category: "runners",
    brand: "nike",
    color: "red",
    size: 40,
    price: 56,
    img: require("./Images/17.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 18,
    gender: "women",
    category: "runners",
    brand: "nike",
    color: "red",
    size: 41,
    price: 58,
    img: require("./Images/18.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 19,
    gender: "men",
    category: "basketball",
    brand: "nike",
    color: "yellow",
    size: 45,
    price: 98,
    img: require("./Images/19.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 20,
    gender: "women",
    category: "runners",
    brand: "nike",
    color: "blue",
    size: 42,
    price: 54,
    img: require("./Images/20.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 21,
    gender: "women",
    category: "casual",
    brand: "nike",
    color: "blue",
    size: 38,
    price: 44,
    img: require("./Images/21.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 22,
    gender: "women",
    category: "casual",
    brand: "nike",
    color: "white",
    size: 35,
    price: 40,
    img: require("./Images/22.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 23,
    gender: "women",
    category: "basketball",
    brand: "nike",
    color: "red",
    size: 46,
    price: 90,
    img: require("./Images/23.png"),
    availableItem: 5,
    orderedItem: 0,
  },
  {
    id: 24,
    gender: "men",
    category: "runners",
    brand: "nike",
    color: "green",
    size: 42,
    price: 85,
    img: require("./Images/24.jpg"),
    availableItem: 5,
    orderedItem: 0,
  },
];

export const cities = [
  {
    id: 0,
    city: "",
  },
  {
    id: 1,
    city: "Tbilisi",
  },
  {
    id: 2,
    city: "Kutaisi",
  },
  {
    id: 3,
    city: "Rustavi",
  },
  {
    id: 4,
    city: "Batumi",
  },
  {
    id: 5,
    city: "Zugdidi",
  },
  {
    id: 6,
    city: "Telavi",
  },
  {
    id: 7,
    city: "Akhaltsikhe",
  },
  {
    id: 8,
    city: "Gori",
  },
  {
    id: 9,
    city: "Abasha",
  },
  {
    id: 10,
    city: "Akhalkalaki",
  },
  {
    id: 11,
    city: "Bagdati",
  },
  {
    id: 12,
    city: "Bolnisi",
  },
  {
    id: 13,
    city: "Borjomi",
  },
  {
    id: 14,
    city: "Dedoplistskaro",
  },
  {
    id: 15,
    city: "Dmanisi",
  },
  {
    id: 16,
    city: "Dusheti",
  },
  {
    id: 17,
    city: "Gardabani",
  },
  {
    id: 18,
    city: "Gurjaani",
  },
  {
    id: 19,
    city: "Adigeni",
  },
  {
    id: 20,
    city: "Vale",
  },
  {
    id: 21,
    city: "Vani",
  },
  {
    id: 22,
    city: "Zestaponi",
  },
  {
    id: 23,
    city: "Tetritskaro",
  },
  {
    id: 24,
    city: "Terjola",
  },
  {
    id: 25,
    city: "Tianeti",
  },
  {
    id: 26,
    city: "Kaspi",
  },
  {
    id: 27,
    city: "Lagodekhi",
  },
  {
    id: 28,
    city: "Lanchkhuti",
  },
  {
    id: 29,
    city: "Marneuli",
  },
  {
    id: 30,
    city: "Martvili",
  },
  {
    id: 31,
    city: "Mestia",
  },
  {
    id: 32,
    city: "Mtskheta",
  },
  {
    id: 33,
    city: "Ninotsminda",
  },
  {
    id: 34,
    city: "Ozurgeti",
  },
  {
    id: 35,
    city: "Oni",
  },
  {
    id: 36,
    city: "Sagarejo",
  },
  {
    id: 37,
    city: "Samtredia",
  },
  {
    id: 38,
    city: "Sachkhere",
  },
  {
    id: 39,
    city: "Senaki",
  },
  {
    id: 40,
    city: "Sighnaghi",
  },
  {
    id: 41,
    city: "Stepantsminda",
  },
  {
    id: 42,
    city: "Surami",
  },
  {
    id: 43,
    city: "Tkibuli",
  },
  {
    id: 44,
    city: "Poti",
  },
  {
    id: 45,
    city: "Qareli",
  },
  {
    id: 46,
    city: "Qobuleti",
  },
  {
    id: 47,
    city: "Kvareli",
  },
  {
    id: 48,
    city: "Chokhatauri",
  },
  {
    id: 49,
    city: "Chkhorotsku",
  },
  {
    id: 50,
    city: "Tsageri",
  },
  {
    id: 51,
    city: "Tsalenjikha",
  },
  {
    id: 52,
    city: "Tsalka",
  },
  {
    id: 53,
    city: "Tsnori",
  },
  {
    id: 54,
    city: "Tskaltubo",
  },
  {
    id: 55,
    city: "Chiatura",
  },
  {
    id: 56,
    city: "Kharagauli",
  },
  {
    id: 57,
    city: "Khashuri",
  },
  {
    id: 58,
    city: "Khobi",
  },
  {
    id: 59,
    city: "Khoni",
  },
  {
    id: 60,
    city: "Jvari",
  },
];
